/*
 *  Licensed Materials - Property of IBM
 *  5725-I43 (C) Copyright IBM Corp. 2011, 2013. All Rights Reserved.
 *  US Government Users Restricted Rights - Use, duplication or
 *  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

//The code below WILL NOT WORK unless you call it inside or after wlCommonInit()
//This file has been generated by the JSONStore Wizard.

;(function () {

	WL.JSONStore.init({
		User : {
			searchFields: {"id":"integer","name":"string","rut":"string"}
		}
	}, {
		// password : 'PleaseChangeThisPassword'
	})

	.then(function () {
		WL.Logger.debug(['Take a look at the JSONStore documentation and getting started module for more details and code samples.',
			'At this point there is no data inside your collection ("User"), but JSONStore is ready to be used.', 
			'You can use WL.JSONStore.get("User").add(data, options) to add data to the collection.',
			'These are some common JSONStore operations: add, replace, remove, change, count, find, findById, findAll.',
			'Most operations are asynchronous, wait until the last operation finished before calling the next one.',
			'Search Fields are not dynamic, call WL.JSONStore.destroy() or the removeCollection API, and then initialize the collection with the new fields.'].join('\n'));
	})

	.fail(function (errObj) {
		WL.Logger.ctx({pretty: true}).error(errObj);
	});

}());